namespace Polytech.Common.Telemetron
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Polytech.Common.Telemetron;
    using Polytech.Common.Telemetron.Configuration;
    using Polytech.Common.Telemetron.Diagnostics;
    using Polytech.Common.Extension;
    using static Polytech.Common.Telemetron.Diagnostics.DiagnosticTrace;

    /// <summary>
    /// A telemetron to use when testing code. This can be used with TestHarnesses to pull the telemetry that is naturally generated by the application into the app.
    /// </summary>
    public class TestTelemetron : TextWriterTelemetronBase, ITelemetronProvider<byte[]>
    {
        private IContextualTestClass testContext;

        private bool EmitTestName;

        private bool EmitCurrentTestOutcome;

        public TestTelemetron(IContextualTestClass testclass, ITestTelemetronConfiguration configuration)
            : base(configuration)
        {
            if (testclass == null)
            {
                throw new ArgumentNullException(nameof(testclass));
            }

            if (testclass.TestContext == null)
            {
                throw new ArgumentNullException(nameof(testclass) + '.' + nameof(testclass.TestContext));
            }

            if (configuration == null)
            {
                throw new ArgumentNullException(nameof(configuration));
            }

            this.EmitTestName = configuration.EmitTestName;
            this.EmitCurrentTestOutcome = configuration.EmitCurrentTestOutcome;

            this.testContext = testclass;
        }

        public IOperation CreateOperation(string operationName)
        {
            try
            {
                ICorrelationContext localCorrelationcontext = this.CorrelationContext;
                long newOperationId = localCorrelationcontext.AddOperation();
                string cc = localCorrelationcontext.ToString();

                this.CorrelationContext = localCorrelationcontext;

                IOperation createdOperation = new TestOperation(this, operationName, newOperationId.GetBase64String(), cc);

                return createdOperation;
            }
            catch (Exception ex)
            {
                DiagnosticTrace.Instance.Error("An unexpected error occurred when attempting to create an operation", ex, "1f3803c8-5a8c-4562-a96b-7069520d8e32");

                return new NullOperation();
            }

        }

        public IOperation CreateOperation(string operationName, byte[] parentContext)
        {
            try
            {
                byte[] capturedCorrelationContext = this.CorrelationContext.Capture();

                CorrelationContext localCorrelationcontext = new CorrelationContext(parentContext);

                long newOperationId = localCorrelationcontext.AddOperation();
                string cc = localCorrelationcontext.ToString();

                this.CorrelationContext = localCorrelationcontext;

                IOperation createdOperation = new TestOperation(this, operationName, newOperationId.GetBase64String(), cc);

                return createdOperation;
            }
            catch (Exception ex)
            {
                DiagnosticTrace.Instance.Error("An unexpected error occurred when attempting to create an operation", ex, "cd11de1d-c4b6-406c-937e-37bc85eb4370");

                return new NullOperation();
            }
        }

        public override bool Trace(EventSeverity eventSeverity, string message, string codePoint = null, Dictionary<string, string> data = null, [CallerMemberName] string callerMemberName = "", [CallerFilePath] string callerFilePath = "", [CallerLineNumber] int callerLineNumber = -1)
        {
            DateTime now = DateTime.UtcNow;

            try
            {
                string log = this.CreateLogMessage(eventSeverity, message, codePoint, data, callerMemberName, callerFilePath, callerLineNumber, now);

                this.testContext.TestContext.WriteLine(log);

                return true;
            }
            catch (Exception ex)
            when (Filter("An unexpected exception occurred when attempting to emit telemetry to the test context.", ex))
            {
                return false;
            }
        }

        public override bool Trace(EventSeverity eventSeverity, string message, Exception exception, string codePoint = null, Dictionary<string, string> data = null, [CallerMemberName] string callerMemberName = "", [CallerFilePath] string callerFilePath = "", [CallerLineNumber] int callerLineNumber = -1)
        {
            return this.Trace(eventSeverity, message, codePoint, data.SafeCombine(exception), callerMemberName, callerFilePath, callerLineNumber);
        }

        protected override void CreateLogMessageAppendSpecificTelemetry(Dictionary<string, string> props)
        {        
            if (this.EmitTestName)
            {
                props[nameof(this.testContext.TestContext.TestName)] = this.testContext.TestContext.TestName;
            }

            if (this.EmitCurrentTestOutcome)
            {
                props[nameof(this.testContext.TestContext.CurrentTestOutcome)] = this.testContext.TestContext.CurrentTestOutcome.ToString();
            }
        }


        /// <summary>
        /// Repply the origin context captured as part of an operation.
        /// </summary>
        /// <param name="capturedContext">the context to reapply.</param>
        void ICorrelatedProvider.ReapplyOriginContext(byte[] capturedContext)
        {
            this.CorrelationContext = new CorrelationContext(capturedContext);
        }
    }
}
